import Lang from './lang';

let Strings = {
  en:{
    contact:'Contact',
    home:'Provisori',
    partners:'Partners',
    facebook:"Facebook",
    instagram:"Instagram",
    deindeal:"Deindeal",
    ranking:"Ranking",
    pricelist:"Price list",
    terms:'Terms of use',
    rules:'Rules',
    register:"Register",
    announcement:"Announcement",
    login:"Login",
    forgetPassword:"Forgot your password ?",
    name:"name",
    firstname:"firstname",
    password:"password",
    question:"Question of the day ",
    response:"Answer",
    responseFinal:"Answer : ",
    error:"Error",
    connectionLost:"Oops .. Check that you are connected to the internet and please retry",
    wrongPassword:"The passwords do not match",
    passwordFormatError:"The password must contain at least 5 characters",
    fildesError:"please complete all fields",
    emailIncorrect:"mail format is wrong",
    loginOK:"You are connected !",
    loginFalse:"email or password is incorrect",
    incorrectAnswer:"Well tried",
    incorrectAnswer2:"Try again",
    incorrectAnswer3:"Did you really read the question?",
    incorrectAnswer4:"Do not forget that a clue is available by clicking on the button",
    prizeWon:"Prize won :",
    offeredBy:"Offered by :",
    clue:"Clue ?",
    pricelist:"Price List",
    conditionsAccepted:"I have read and accept the terms and conditions",
    conditionsNotAccepted:"Please accept the terms of use",
    registerInfo:"These informations are useful for contacting you if you win prizes.",
    introduction:"Welcome to Provisori! Every day from 12h30: try to solve a new enigma. And late afternoon: find out if you have won the prize of the day!",
    lastQuestions:"Last questions",
  },

  fr:{
    contact:'Contact',
    home:'Provisori',
    partners:'Partenaires',
    announcement:"Annonces",
    pricelist:"Liste de prix",
    facebook:"Facebook",
    instagram:"Instagram",
    deindeal:"Deindeal",
    ranking:"Classements",
    terms:'Conditions d\'utilisation',
    rules:"Règles du jeu",
    register:"S'enregister",
    login:"Se connecter",
    forgetPassword:"Mot de passe oublié",
    name:"nom",
    firstname:"prenom",
    password:"mot de passe",
    question:"Question",
    response:"Votre réponse",
    responseFinal:"Réponse :",
    error:"Erreur",
    connectionLost:"Oups.. Vérifiez que vous êtes bien connecté à internet et réessayez",
    wrongPassword:"les mots de passe ne correspondent pas",
    passwordFormatError:"The password must be at least 5 characters long",
    fildesError:"veuillez remplir tous les champs",
    emailIncorrect:"Le format du mail n'est pas correct",
    loginOK:"Vous êtes maintenant connecté !",
    loginFalse:"l'email ou le mot de passe est incorrect",
    incorrectAnswer:"Bien essayé",
    incorrectAnswer2:"Essaie encore",
    incorrectAnswer3:"As-tu vraiment bien lu la question?",
    incorrectAnswer4:"N'oublie pas qu'un indice est disponible en bas de la question dans le bouton rond \"indice ?\"",
    prizeWon:"Prix gagné :",
    offeredBy:"Offert par :",
    clue:"indice ?",
    conditionsAccepted:"J'ai lu et j'accepte les conditions générales",
    conditionsNotAccepted:"Veuillez accepter les conditions d'utilisation",
    registerInfo:"Ces informations nous sont utiles pour vous contacter si vous gagnez des prix.",
    introduction:"Bienvenue dans Provisori! Tous les jours dès 12h30: tentez de résoudre une nouvelle énigme. Et en fin de journée: découvrez si vous avez remporté le prix du jour mis en jeu! ",
    lastQuestions:"Dernières questions",
  },

  it:{
    contact:'Contatti',
    home:'Provisori',
    partners:'Partners',
    facebook:"Facebook",
    announcement:"Annonces",
    instagram:"Instagram",
    deindeal:"Deindeal",
    ranking:"Classifica",
    pricelist:"Preisliste",
    terms:'Condizioni d\'uso',
    rules:'Regole',
    register:"Registrare",
    login:"Accedi",
    forgetPassword:"Password dimenticata ?",
    name:"Cognome",
    firstname:"Nome",
    password:"Password",
    question:"Enigma del giorno",
    response:"Risposta",
    responseFinal:"Risposta : ",
    error:"Errore",
    connectionLost:"Oups.. Vérifiez que vous êtes bien connecté à internet et relancer l'application",
    wrongPassword:"Password sbagliata",
    passwordFormatError:"La password deve contare almeno 5 caratteri",
    fildesError:"completare per favore tutti i campi",
    emailIncorrect:"formato email sbagliato",
    loginOK:"Sei connesso !",
    loginFalse:"email o password sbagliati",
    incorrectAnswer:"Ben provato",
    incorrectAnswer2:"Riprova",
    incorrectAnswer3:"Hai davvero letto la domanda?",
    incorrectAnswer4:"Vergessen Sie nicht, dass Sie einen Tipp haben wenn Sie auf den runden \"Tipp ?\" Knopf drücken",
    prizeWon:"Premio vinto:",
    offeredBy:"Offerto da :",
    clue:"Indizio ?",
    conditionsAccepted:"Ho letto e accetto i termini e le condizioni",
    conditionsNotAccepted:"Si prega di accettare i termini e le condizioni",
    registerInfo:"Diese Informationen sind nützlich, um Sie zu kontaktieren, wenn Sie Preise gewinnen.",
    introduction:"Benvenuto in Provisori! Ogni giorno dalle 12h30: prova a risolvere un nuovo enigma. E alle 19h: scopri se hai vinto il premio del giorno!",
    lastQuestions:"Last questions",
},

  de:{
    contact:'Kontakt',
    home:'Provisori',
    partners:'Partner',
    facebook:"Facebook",
    instagram:"Instagram",
    deindeal:"Deindeal",
    announcement:"Ankündigung",
    ranking:"Ranking",
    pricelist:"Preisliste",
    terms:'Nutzungsbedingungen',
    rules:'Spielregeln',
    register:"Registrieren",
    login:"Anmelden",
    forgetPassword:"Passwort vergessen?",
    name:"Name",
    firstname:"Vorname",
    password:"Passwort",
    question:"Frage des Tages",
    response:"Ihre Antwort",
    responseFinal:"Antwort: ",
    error:"Fehler",
    connectionLost:"Ups… Stellen Sie sicher, dass Sie eine Internetverbindung haben und versuchen Sie es erneut",
    wrongPassword:"Die Passwörter stimmen nicht überein",
    passwordFormatError:"Das Passwort muss mindestens 5 Zeichen lang sein",
    fildesError:"Bitte füllen Sie alle Felder aus",
    emailIncorrect:"E-Mail Format Falsch",
    loginOK:"Sie sind nun angemeldet!",
    loginFalse:"E-Mail oder Passwort ist falsch",
    incorrectAnswer:"Netter Versuch",
    incorrectAnswer2:"Versuchen Sie es nochmal",
    incorrectAnswer3:"Haben Sie die Frage richtig gelesen?",
    incorrectAnswer4:"Vergessen Sie nicht, dass Sie einen Hinweis haben wenn Sie auf den Knopf oben rechts drücken",
    prizeWon:"Gewonnener Preis:",
    offeredBy:"von unserem Partner:",
    clue:"Tipp?",
    conditionsAccepted:"Ich habe die AGB gelesen und akzeptiere sie.",
    conditionsNotAccepted:"Bitte akzeptieren Sie die AGB",
    registerInfo:"Wie benötigen diese Daten, um Sie im Fall eines Gewinns benachrichtigen zu können.",
    introduction:"Willkommen bei Provisori! Versuchen Sie jeden Tag ab 12:30 Uhr ein neues Rätsel zu lösen. Und finden Sie am Ende des Tages heraus, ob Sie den Preis des Tages gewonnen haben!",
    lastQuestions:"Letzte Fragen",
  },

};

module.exports = (async function() {
  lang = await Lang.getLang();
  return Strings[lang];
})()
