let strings = {
    contact:'Contact',
    contact_us:'Nous contacter',
    home:'Provisori',
    answers: 'Réponses',
    follow: 'Suivez-nous',
    partners:'Partenaires',
    announcement:"Annonces",
    pricelist:"Liste de prix",
    facebook:"Facebook",
    instagram:"Instagram",
    deindeal:"Deindeal",
    rank: "Position",
    ranking:"Classement",
    terms:"Conditions d'utilisation",
    rules:"Règles du jeu",
    register:"S'enregister",
    login:"Se connecter",
    login_link_register_text: "Pas encore de compte ? S'enregister",
    playLoginFalse: 'Vous devez être connecté pour jouer au jeu.',
    playLoginFalse2: 'Allez dans le menu et cliquez sur «Se connecter».',    
    register_link_login_text: "Déjà un compte ? Se connecter",
    forgetPassword:"Mot de passe oublié",
    name:"Nom",
    firstname:"Prénom",
    password:"Mot de passe",
    question:"Question",
    responses: "Réponses",
    response:"Votre réponse",
    username:"Nom d'utilisateur",
    responseFinal:"Réponse",
    error:"Erreur",
    connectionLost:"Oups.. Vérifiez que vous êtes bien connecté à internet et réessayez",
    wrongPassword:"les mots de passe ne correspondent pas",
    passwordFormatError:"The password must be at least 5 characters long",
    fildesError:"veuillez remplir tous les champs",
    emailIncorrect:"Le format du mail n'est pas correct",
    loginOK:"Vous êtes maintenant connecté !",
    loginFalse:"l'email ou le mot de passe est incorrect",
    incorrectAnswer:"Bien essayé",
    incorrectAnswer2:"Essaie encore",
    incorrectAnswer3:"As-tu vraiment bien lu la question?",
    incorrectAnswer4:"N'oublie pas qu'un indice est disponible en bas de la question dans le bouton rond \"indice ?\"",
    prizeWon:"Prix gagné :",
    offeredBy:"Offert par :",
    clue:"Indice",
    enigma: 'Énigme',
    conditionsAccepted:"J'ai lu et j'accepte les conditions générales",
    conditionsNotAccepted:"Veuillez accepter les conditions d'utilisation",
    registerInfo:"Ces informations nous sont utiles pour vous contacter si vous gagnez des prix.",
    introduction:"Bienvenue dans Provisori! Tous les jours dès 12h30: tentez de résoudre une nouvelle énigme. Et en fin de journée: découvrez si vous avez remporté le prix du jour mis en jeu! ",
    lastQuestions:"Dernières questions",
    prix: 'Prix',
    enigmaNotPresent: "Pas d'énigme pour le moment",
    enigmaAnswer: "La réponse à l'énigme",
    winner: "Le gagnant a été tiré au sort !",
    win: "remporte",
    cancel: "Annuler",
    play: 'Vous jouez pour ',
    points: 'points',
    points_maj: 'Points',
    findAnswer: 'Vous avez trouvé',
    noPrice: 'Aucun prix disponible pour le moment',
    confirm:'Confirmation',
    confirm_text: 'Si vous souhaitez supprimer votre compte, vous pouvez nous écrire un email et nous procéderons à la suppression de votre compte dans les plus bref délais',
    nb_points: 'Nombre de points',
    nb_tentatives: 'Nombre de tentatives',
    nb_rep: 'Nombre de réponses trouvées depuis le début du mois',
    util: 'Nom d\'utilisateur',
    delete: 'Effacer mon compte',
    account: 'Mon compte',
    found_resp: 'Félicitations!',
    found_resp_text1: 'Félicitations, tu as trouvé la bonne réponse ! ',
    found_resp_text2: 'Reconnecte-toi ce soir dès 19h pour découvrir plus de détails sur l\'énigme. ',
    found_resp_text3: '! Vous allez recevoir un email vous expliquant comment procéder à l\'utilisation du bon',
    see_price: 'Voir le prix'
  }

  module.exports = (function() {
    return strings;
  })()
