let strings = {
    contact:'Kontakt',
    contact_us:'Kontaktiere uns',
    home:'Provisori',
    answers: 'Antworten',
    follow: 'Folgen Sie uns',
    partners:'Partner',
    facebook:"Facebook",
    instagram:"Instagram",
    deindeal:"Deindeal",
    announcement:"Ankündigung",
    ranking:"Ranking",
    pricelist:"Preisliste",
    terms:'Nutzungsbedingungen',
    rules:'Spielregeln',
    register:"Registrieren",
    login:"Anmelden",
    login_link_register_text: "Noch keinen Account? Registrieren",
    register_link_login_text: "Sie haben bereits ein Konto? Einloggen",
    playLoginFalse: "Sie müssen eingeloggt sein, um das Spiel zu spielen",
    playLoginFalse2: 'Allez dans le menu et cliquez sur «Se connecter».',
    forgetPassword:"Passwort vergessen?",
    name:"Name",
    firstname:"Vorname",
    password:"Passwort",
    username:"Nutzername",
    question:"Frage des Tages",
    rank: "Rang",
    responses: "Antworten",
    response:"Ihre Antwort",
    responseFinal:"Antwort",
    error:"Fehler",
    connectionLost:"Ups… Stellen Sie sicher, dass Sie eine Internetverbindung haben und versuchen Sie es erneut",
    wrongPassword:"Die Passwörter stimmen nicht überein",
    passwordFormatError:"Das Passwort muss mindestens 5 Zeichen lang sein",
    fildesError:"Bitte füllen Sie alle Felder aus",
    emailIncorrect:"E-Mail Format Falsch",
    loginOK:"Sie sind nun angemeldet!",
    loginFalse:"E-Mail oder Passwort ist falsch",
    incorrectAnswer:"Netter Versuch",
    incorrectAnswer2:"Versuchen Sie es nochmal",
    incorrectAnswer3:"Haben Sie die Frage richtig gelesen?",
    incorrectAnswer4:"Vergessen Sie nicht, dass Sie einen Hinweis haben wenn Sie auf den Knopf oben rechts drücken",
    prizeWon:"Gewonnener Preis:",
    offeredBy:"von unserem Partner:",
    clue:"Tipp",
    enigma: 'Rätsel',
    conditionsAccepted:"Ich habe die AGB gelesen und akzeptiere sie.",
    conditionsNotAccepted:"Bitte akzeptieren Sie die AGB",
    registerInfo:"Wie benötigen diese Daten, um Sie im Fall eines Gewinns benachrichtigen zu können.",
    introduction:"Willkommen bei Provisori! Versuchen Sie jeden Tag ab 12:30 Uhr ein neues Rätsel zu lösen. Und finden Sie am Ende des Tages heraus, ob Sie den Preis des Tages gewonnen haben!",
    lastQuestions:"Letzte Fragen",
    prix: 'Preis',
    enigmaNotPresent: "Noch kein Rätsel",
    enigmaAnswer: "Die Lösung des Rätsels",
    win: "gewinnt",
    cancel: 'Stornieren',
    play: 'Du spielst für ',
    points: 'Punkte',
    points_maj: 'Punkte',
    findAnswer: 'Antwort gefunden ',
    noPrice: 'Momentan kein Preis verfügbar',
    confirm: 'Bestätigung',
    confirm_text: 'Wenn Sie Ihr Konto löschen möchten, können Sie uns eine E-Mail schreiben und wir werden Ihr Konto so schnell wie möglich löschen.',
    nb_points: 'Anzahl der Punkte',
    nb_tentatives: 'Anzahl der Versuche',
    nb_rep: 'Anzahl der gefundenen Antworten seit Beginn des Monats',
    util: 'Benutzername',
    delete: 'Mein Konto löschen',
    account: 'Mein Konto',
    found_resp: 'Glückwunsch!',
    found_resp_text1: 'Herzlichen Glückwunsch, du hast die richtige Antwort gefunden! ',
    found_resp_text2: 'Verbinde dich heute Abend ab 19 Uhr erneut, um mehr Details über das Rätsel zu erfahren. ',
    found_resp_text3: '! Sie erhalten eine E-Mail mit Anweisungen zur Verwendung des Gutscheins',
    see_price: 'Preis anzeigen'
};

module.exports = (function() {
  return strings;
})()
